### ISSUE TITLE
Async Get Item at Location not working

### ISSUE THREAD

**Issue by geronimo078** [Theuntextured/AsynConveyorPlugin#3]
The function does not return any items.

**Comment by Theuntextured** [comment]
You sure that when you're trying to access the variables, you're dragging off of the bottom exec node rather than the top?

**Comment by geronimo078** [comment]
Yes, i used the completed exec node. I also replaced it with the "Async Extract Item" function as a test. That worked but "Async Get Item at Location" does not. All tests are using Unreal 5.3.1
