### ISSUE TITLE
Merger does not change the input correctly

### ISSUE THREAD

**Issue by geronimo078** [Theuntextured/AsynConveyorPlugin#5]
Since the last update, merger does not change the input correctly. these should always alternate from the different inputs.

https://github.com/Theuntextured/AsynConveyorPlugin/assets/39373595/c4fabea3-403e-4063-8a1b-d697430272d0

https://github.com/Theuntextured/AsynConveyorPlugin/assets/39373595/c4ca0af2-b608-4f10-a149-691193bdbed4

**Comment by DissociatedGames** [comment]
was able to replicate this also. It doesnt do it at first but if you let the belts fill up then start removing items at the end it will happen.

**Comment by Theuntextured** [comment]
I did consider this. I am fully aware of this issue. At the moment I considered it a feature rather than a bug (yes, annoying answer, I know). However, I have an idea of how I can fix it and I will try to implement it tomorrow. Hopefully it works!

**Comment by Theuntextured** [comment]
Changes should be on the Epic Games Launcher in a few hours! Just waiting on Epic!
