### ISSUE TITLE
Async Get Item at Location

### ISSUE THREAD

**Issue by geronimo078** [Theuntextured/AsynConveyorPlugin#6]
Return Value "Transform" not returning anything. The value is always zero.

**Comment by Theuntextured** [comment]
It worked last time I checked... But I guess I somehow broke it while fixing other bugs.... Will be an easy fix!

**Comment by Theuntextured** [comment]
nah, its a bug.

**Comment by geronimo078** [comment]
Ok, i use this to check if it is the right item on the belt before i remove it.

**Comment by Theuntextured** [comment]
As I said, it should be an easy fix. The way that async actions are done is that they are queued and then the normal function is simply called on a separate thread once all items have been processed. Then the return values are passed onto the async action task to output to the blueprint node. It is very simple, so if it doesn't work, its probably just me being stupid and forgetting a single line of code or something like that.

**Comment by geronimo078** [comment]
makes sense, thanks for the explanation.
